---
title: "p8160_hw1_zl2860"
author: "Zongchao Liu"
date: "2/16/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(tidyverse)
library(glmnet)
library(caret)
library(ModelMetrics) 
```

# load data
```{r}
set.seed(886)
train = read_csv("./solubility_train.csv")
test = read_csv("./solubility_test.csv")
train_x = model.matrix(Solubility ~ . , train)[,-ncol(train)]
train_y = train$Solubility
test_x = model.matrix(Solubility ~ . , test)[,-ncol(test)]
test_y = test$Solubility
```

# 1. ls regression

```{r}
ctrl1  = trainControl(method = "repeatedcv", number = 10, repeats = 5)
lm.fit = train(train_x, 
               train_y,
               method = "lm",
               trControl = ctrl1)

pred_test_fit = predict(lm.fit,newx = test_x)
mse(test_y,pred_test_fit)

```

#2. ridge

```{r} 
ridge.fit = train(x = train_x,
                  y = train_y,
                  method = "glmnet",
                  tuneGrid = expand.grid(alpha = 0,
                                         lambda = exp(seq(-10,5,length = 100))),
                  trControl = ctrl1)

plot(ridge.fit,xTrans = function(x) log(x))


```

# 3 . lasso

```{r}
set.seed(886)
lasso.fit = train(train_x,
                  train_y,
                  method = "glmnet",
                  tuneGrid = expand.grid(alpha = 1,
                                         lambda = exp(seq(-6,-4,length = 200))),
                  preProc = c("center","scale"),
                  trControl = ctrl1)
log(0.0006)

lasso.fit$bestTune

plot(lasso.fit, xTrans = function(x) log(x))

coef = coef(lasso.fit$finalModel,lasso.fit$bestTune$lambda)
```

# d. pcr

```{r}
set.seed(886)
pcr.fit <- train(x = train_x, 
                 y = train_y,
                 method = "pcr",
                 tuneLength = 200,
                 trControl = ctrl1,
                 preProc = c("center", "scale"))

trans <- preProcess(train_x, method = c("center", "scale"))

predy2.pcr2 <- predict(pcr.fit$finalModel, newdata = predict(trans, test_x),ncomp = pcr.fit$bestTune$ncomp)


mse(test_y, predy2.pcr2)

ggplot(pcr.fit, highlight = T) + theme_bw()


```

#
```{r}
resamp = resamples(list(lasso = lasso.fit,
                        ridge = ridge.fit,
                        pcr = pcr.fit,
                        lm = lm.fit))

summary(resamp)
parallelplot(resamp,metric = "RMSE")
bwplot(resamp, metric = "RMSE")
```

